### ISSUE TITLE
support for sass and scss files

### ISSUE THREAD

**Issue by effkay** [skammer/vim-css-color#1]
Hi there,

love your plugin. Any way this could work with sass/scss files? Syntax within files wouldn't need to be adapted, just extend plugin so it also works on files with extensions other than css. Digging around myself but I've never written a vim plugin so I'm a bit lost there.

cheers,
fk

**Comment by gf3** [comment]
+1

**Comment by skammer** [comment]
Great idea! I'm a little short on time right now due to exams and stuff, but I will look into this as soon as I can. As far as I know, existing code should nicely fit both sass/scss and less. So the problem is to find a way to extend existing syntaxes without breaking anything.

**Comment by keeganstreet** [comment]
Hey guys, you can get this plugin to work with your SCSS files by telling Vim to treat them as CSS files. Just add the following line to your .vimrc

`au BufRead,BufNewFile *.scss set filetype=css`

**Comment by effkay** [comment]
Thanks for the hint, this is what I needed!
