### ISSUE TITLE
vim-css-color slows vi/vim setup time in terminal/iTrem

### ISSUE THREAD

**Issue by yam-liu** [skammer/vim-css-color#16]
vim becomes slow no matter whether i set  let g:cssCol.....=1 or not.  (NOT in MacVim but in MacVim.app/Contents/MacOS/Vim)

I don't know if this script results in setup slowly

the following is got by run

> vi somefile --startuptime 

/////////////////////////
times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.013  000.013: --- VIM STARTING ---
000.118  000.105: Allocated generic buffers
000.552  000.434: locale set
000.565  000.013: window checked
001.242  000.677: inits 1
001.326  000.084: parsing arguments
001.332  000.006: expanding arguments
001.352  000.020: shell init
001.674  000.322: Termcap init
001.695  000.021: inits 2
001.800  000.105: init highlight
002.026  000.153  000.153: sourcing $VIM/vimrc
021.863  019.586  019.586: sourcing /usr/share/vim/vim73/filetype.vim
022.043  000.056  000.056: sourcing /usr/share/vim/vim73/ftplugin.vim 

…….省略若干

181.365  004.024  004.024: sourcing /usr/share/vim/vim73/syntax/vb.vim
183.938  002.283  002.283: sourcing /usr/share/vim/vim73/syntax/css.vim
**3973.674  3789.661  3789.661: sourcing /Users/ooops/.vim/bundle/vim-css-color/after/syntax/css.vim**
3975.022  3803.613  003.521: sourcing /usr/share/vim/vim73/syntax/html.vim
3975.821  3804.635  001.022: sourcing /usr/share/vim/vim73/syntax/markdown.vim
3980.080  008.641: opening buffers
3980.315  000.235: BufEnter autocommands
3980.318  000.003: editing files in windows
3981.407  000.338  000.338: sourcing /Users/ooops/.vim/bundle/vim-powerline/autoload/Pl.vim
3982.196  000.647  000.647: sourcing /Users/ooops/.vim/bundle/vim-powerline/Powerline_default_default_fancy.cache
3983.838  000.112  000.112: sourcing /Users/ooops/.vim/bundle/vim-powerline/autoload/Pl/Match.vim
3984.495  003.080: VimEnter autocommands
3984.498  000.003: before starting main loop
3986.359  000.280  000.280: sourcing /Users/ooops/.vim/bundle/vim-powerline/autoload/Powerline/Functions.vim
3986.889  002.111: first screen update
3986.891  000.002: --- VIM STARTED ---

**Comment by ap** [comment]
[Use my fork](/ap/vim-css-color), @ooopscc. I forked it to make it faster, in the end I rewrote everything and now it flies.

**Comment by yam-liu** [comment]
@ap Thanks, it works fine.
