### ISSUE TITLE
not working with colon(:)

### ISSUE THREAD

**Issue by qianyingshuo** [skammer/vim-css-color#21]
In my PC, it working like this:

![aa](https://cloud.githubusercontent.com/assets/4676914/4173722/608042ea-3563-11e4-9f70-bcc5ef8cb705.png)

what should i do?
Thanks a lot.

**Comment by ap** [comment]
Maybe try [my fork](/ap/vim-css-color)?

**Comment by qianyingshuo** [comment]
thank for ap, The question has been saved.
