### ISSUE TITLE
Conflict between junegunn/rainbow_parentheses.vim, cakebaker/scss-syntax.vim and ap/vim-css-color

### ISSUE THREAD

**Issue by JulioJu** [skammer/vim-css-color#25]
Hi,

With the vimrc at the end of this message, ap/vim-css-color doesn't work correctly. Colors are highlighted when the line is commented. For example in a css file named `test.css` only line three — commented — is correctly highlighted. It's strange, because "`Plug 'cakebaker/scss-syntax.vim', { 'for': ['sass', 'scss'] }`" tells 'cakebaker/scss-syntax.vim' is only activated in sass or scss files, but this bug impacts also css files. 

In the fallowing vimrc, if we remove only plugin https://github.com/kien/rainbow_parentheses.vim OR https://github.com/cakebaker/scss-syntax.vim', vim-css-color works correctly.

The fork  https://github.com/gko/vim-coloresque works fine with 'https://github.com/cakebaker/scss-syntax.vim' and 'https://github.com/kien/rainbow_parentheses.vim'.
```
/* test.css */
div {
/*	color:red; */
color: red;
}
```
```
" vimrc
call plug#begin('~/.vim/plugged')

" Rainbow_parentheses.vim
" https://github.com/kien/rainbow_parentheses.vim
" Better Rainbow Parentheses
Plug 'junegunn/rainbow_parentheses.vim'

" CSS color
" Highlight colors in css files
" Plug 'skammer/vim-css-color'
Plug 'ap/vim-css-color'

" scss-syntax.vim
" https://github.com/cakebaker/scss-syntax.vim
" Vim syntax file for scss (Sassy CSS)
Plug 'cakebaker/scss-syntax.vim', { 'for': ['sass', 'scss'] }

call plug#end()
filetype plugin indent on

let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}']]
au BufEnter * RainbowParentheses
```

**Comment by ap** [comment]
I’m not sure why you would report this issue to @skammer if the bug is in my fork…? At least, the codebases haven’t had anything in common in half a decade. Unless I’m missing something: please report this over in my issues… and presumably, close the issue here (I can’t say whether @skammer cares).

**Comment by skammer** [comment]
@ap speaks truth. Head over to https://github.com/ap/vim-css-color.
