### ISSUE TITLE
Update time about 3 seconds

### ISSUE THREAD

**Issue by eduardoarandah** [skammer/vim-css-color#29]
Every time I enter a buffer, lags about 4 seconds. 

I tried this configuration but didn't work. 

```
let g:cssColorVimDoNotMessMyUpdatetime = 1
```

tested in: 

- tmux + nvim
- tmux + vim
- vim
- nvim

I don't know what info you might need to debug this

**Comment by ap** [comment]
This plugin has had no changes for almost a decade. I suggest switching to [my rewrite of the plugin](/ap/vim-css-color), for which my main impetus was speed optimisation.
