### ISSUE TITLE
Fix: "white" gets highlighted in white-space:;

### ISSUE THREAD

**Issue by kien** [skammer/vim-css-color#9]
e.g.
![img](http://i.imgur.com/E8YRV.png)

A fix is to change this line

``` vim
exe 'syn keyword '.group.' '.a:name.' contained'
```

or this in @ap's fork

``` vim
exe 'syn keyword' group a:name 'contained'
```

to use `syn match`:

``` vim
exe 'syn match '.group.' /:[^:]*\zs'.a:name.'/ contained'
```

**Comment by ap** [comment]
That breaks highlighting multiple colours on the same line.

**Comment by ap** [comment]
More importantly, I don’t even get that behaviour in my fork! At least I just tried it and Vim didn’t highlight the “white” part in `white-space`.

**Comment by kien** [comment]
That's odd, I just tried again with your fork and it definitely highlights "white" in white-space. And technically, it should.

Screenshot for good measure:
![img](http://i.imgur.com/WwV3I.png)

**Comment by kien** [comment]
Again with a blank installation of Vim with nothing but `after/syntax/css.vim`:

![img](http://i.imgur.com/hhSfB.png)

vimrc:

``` vim
set nocompatible
colo blue
syntax enable
```

**Comment by kien** [comment]
Ok, this works for me:

``` vim
exe 'syn match '.group.' /\(:[^:]*\zs'.a:name.'\)\+/ contained'
```

![img](http://i.imgur.com/Y4KtQ.png)

**Comment by ap** [comment]
![](http://i.imgur.com/lo1Ny.png)

**Comment by ap** [comment]
Oh yes. Turns out I had [a fix for this in my `.vimrc`](https://github.com/ap/dotvim/blob/1e4756904152ed3004b6b89f6afea523c194fb20/vimrc#L434).

I think including that is the right fix, instead of hacking up the `syn keyword` command into a `syn match`.

**Comment by ap** [comment]
OK, I’ve done that in [my fork](https://github.com/ap/vim-css-color).

**Comment by kien** [comment]
Cool, updated my css.vim.

**Comment by kien** [comment]
It seems that Vim's bundled CSS highlighting has a bug with `background-repeat` and `iskeyword` causes it to not get highlighted correctly. Also, the `iskeyword` fix changes the `w` text object to encompass the entire CSS property (entire left hand side).

Type `vaw` with `iskeyword+=-`
![img](http://i.imgur.com/BauB0.png)

and without it; notice the subtle differences:
![img](http://i.imgur.com/dg20r.png)

This gets annoying when you want to use something like `ciw` to only change one word in a CSS property
e.g. `top` in `border-top-width:;`

I've switched back to `syn match` for the time being.
